<?php

use Illuminate\Database\Seeder;

class CarModelsTableSeeder extends Seeder
{
	protected $table = 'car_models';
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$currentTime = time(); 
        //
        $data_arr = [
            [
            	"iId" => 1,
            	"vlang" => "zh-tw",
                "vCarModelName" => "CAMRY(HYBRID)",
                "vCarModelNameE" => "CAMRY(HYBRID)",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 2,
            	"vlang" => "zh-tw",
                "vCarModelName" => "COROLLA ALTIS-X",
                "vCarModelNameE" => "COROLLA ALTIS-X",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 3,
            	"vlang" => "zh-tw",
                "vCarModelName" => "ALTIS",
                "vCarModelNameE" => "ALTIS",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 4,
            	"vlang" => "zh-tw",
                "vCarModelName" => "YARIS",
                "vCarModelNameE" => "YARIS",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 5,
            	"vlang" => "zh-tw",
                "vCarModelName" => "PRIUS-C",
                "vCarModelNameE" => "PRIUS-C",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 6,
            	"vlang" => "zh-tw",
                "vCarModelName" => "PRIUS-a",
                "vCarModelNameE" => "PRIUS-a",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 7,
            	"vlang" => "zh-tw",
                "vCarModelName" => "PRIUS",
                "vCarModelNameE" => "PRIUS",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 8,
            	"vlang" => "zh-tw",
                "vCarModelName" => "VIOS",
                "vCarModelNameE" => "VIOS",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 9,
            	"vlang" => "zh-tw",
                "vCarModelName" => "RAV4",
                "vCarModelNameE" => "RAV4",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 10,
            	"vlang" => "zh-tw",
                "vCarModelName" => "WISH",
                "vCarModelNameE" => "WISH",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 11,
            	"vlang" => "zh-tw",
                "vCarModelName" => "PREVIA",
                "vCarModelNameE" => "PREVIA",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 12,
            	"vlang" => "zh-tw",
                "vCarModelName" => "INNOVA",
                "vCarModelNameE" => "INNOVA",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 13,
            	"vlang" => "zh-tw",
                "vCarModelName" => "PRADO",
                "vCarModelNameE" => "PRADO",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 14,
            	"vlang" => "zh-tw",
                "vCarModelName" => "ALPHARD",
                "vCarModelNameE" => "ALPHARD",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 15,
            	"vlang" => "zh-tw",
                "vCarModelName" => "TERCEL",
                "vCarModelNameE" => "TERCEL",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 16,
            	"vlang" => "zh-tw",
                "vCarModelName" => "SIENTA",
                "vCarModelNameE" => "SIENTA",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 17,
            	"vlang" => "zh-tw",
                "vCarModelName" => "SIENNA",
                "vCarModelNameE" => "SIENNA",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 18,
            	"vlang" => "zh-tw",
                "vCarModelName" => "PREMIO",
                "vCarModelNameE" => "PREMIO",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
            [
            	"iId" => 19,
            	"vlang" => "zh-tw",
                "vCarModelName" => "C_HR",
                "vCarModelNameE" => "C_HR",
                "vCarModelImg" => "",
                "iCarModelType" => 0,
                "vCarModelAge" => "",
                "iCarBrandId" => 1,
                "vSummary" => "",
                "vDetail" => "",
                "vCarModelUrl" => "",
                "iRank" => 1,
                "iCreateTime" => $currentTime,
                "iUpdateTime" => $currentTime,
                "iStatus" => 1,
                "bDel" => 0
            ],
        ]; 

        DB::table($this->table)->delete();
        DB::table($this->table)->insert($data_arr);   
    }
}
